name: Build and test

on:
  push:
    branches-ignore:
      - 'dev'
      - 'main'
jobs:
  build-deploy:
    name: build and test
    runs-on: ubuntu-latest
    env:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:testdb
      SPRING_DATASOURCE_USERNAME: 'sa'
      SPRING_DATASOURCE_PASSWORD: 'password'
      TEST_USER_USERNAME: 'john'
      TEST_USER_PASSWORD: 'johndoe'
      JWT_SECRETKEY: 'secret'

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Unit tests
        run: mvn -B test --file pom.xml

      - name: Build the application
        run: mvn -B package --file pom.xml
